{
  "functions": [
    {
      "name": "FloatMul",
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "oper1",
          "decl": "float oper1"
        },
        {
          "type": "float",
          "name": "oper2",
          "decl": "float oper2"
        }
      ]
    },
    {
      "name": "FloatDiv",
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "dividend",
          "decl": "float dividend"
        },
        {
          "type": "float",
          "name": "divisor",
          "decl": "float divisor"
        }
      ]
    },
    {
      "name": "FloatAdd",
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "oper1",
          "decl": "float oper1"
        },
        {
          "type": "float",
          "name": "oper2",
          "decl": "float oper2"
        }
      ]
    },
    {
      "name": "FloatSub",
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "oper1",
          "decl": "float oper1"
        },
        {
          "type": "float",
          "name": "oper2",
          "decl": "float oper2"
        }
      ]
    },
    {
      "name": "FloatFraction",
      "docStart": 3394,
      "docEnd": 3508,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "RoundToZero",
      "docStart": 3554,
      "docEnd": 3693,
      "kind": "native",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "RoundToCeil",
      "docStart": 3735,
      "docEnd": 3877,
      "kind": "native",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "RoundToFloor",
      "docStart": 3919,
      "docEnd": 4060,
      "kind": "native",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "RoundToNearest",
      "docStart": 4103,
      "docEnd": 4219,
      "kind": "native",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "FloatCompare",
      "docStart": 4264,
      "docEnd": 4607,
      "kind": "native",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "fOne",
          "decl": "float fOne"
        },
        {
          "type": "float",
          "name": "fTwo",
          "decl": "float fTwo"
        }
      ]
    },
    {
      "name": "SquareRoot",
      "docStart": 4661,
      "docEnd": 4832,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "Pow",
      "docStart": 4875,
      "docEnd": 5062,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        },
        {
          "type": "float",
          "name": "exponent",
          "decl": "float exponent"
        }
      ]
    },
    {
      "name": "Exponential",
      "docStart": 5114,
      "docEnd": 5234,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "Logarithm",
      "docStart": 5278,
      "docEnd": 5464,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        },
        {
          "type": "float",
          "name": "base",
          "decl": "float base"
        }
      ]
    },
    {
      "name": "Sine",
      "docStart": 5523,
      "docEnd": 5643,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "Cosine",
      "docStart": 5680,
      "docEnd": 5802,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "Tangent",
      "docStart": 5841,
      "docEnd": 5964,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "FloatAbs",
      "docStart": 6004,
      "docEnd": 6123,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "ArcTangent",
      "docStart": 6164,
      "docEnd": 6294,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "angle",
          "decl": "float angle"
        }
      ]
    },
    {
      "name": "ArcCosine",
      "docStart": 6337,
      "docEnd": 6466,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "angle",
          "decl": "float angle"
        }
      ]
    },
    {
      "name": "ArcSine",
      "docStart": 6508,
      "docEnd": 6635,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "angle",
          "decl": "float angle"
        }
      ]
    },
    {
      "name": "ArcTangent2",
      "docStart": 6675,
      "docEnd": 6842,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "x",
          "decl": "float x"
        },
        {
          "type": "float",
          "name": "y",
          "decl": "float y"
        }
      ]
    },
    {
      "name": "RoundFloat",
      "docStart": 6891,
      "docEnd": 7085,
      "kind": "stock",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "DegToRad",
      "docStart": 10766,
      "docEnd": 10861,
      "kind": "stock",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "angle",
          "decl": "float angle"
        }
      ]
    },
    {
      "name": "RadToDeg",
      "docStart": 10937,
      "docEnd": 11032,
      "kind": "stock",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "angle",
          "decl": "float angle"
        }
      ]
    },
    {
      "name": "GetURandomInt",
      "docStart": 11108,
      "docEnd": 11286,
      "kind": "native",
      "returnType": "int",
      "arguments": []
    },
    {
      "name": "GetURandomFloat",
      "docStart": 11319,
      "docEnd": 11520,
      "kind": "native",
      "returnType": "float",
      "arguments": []
    },
    {
      "name": "SetURandomSeed",
      "docStart": 11557,
      "docEnd": 11819,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "const int[]",
          "name": "seeds",
          "decl": "const int[] seeds"
        },
        {
          "type": "int",
          "name": "numSeeds",
          "decl": "int numSeeds"
        }
      ]
    },
    {
      "name": "SetURandomSeedSimple",
      "docStart": 11885,
      "docEnd": 12072,
      "kind": "stock",
      "returnType": "void",
      "arguments": [
        {
          "type": "int",
          "name": "seed",
          "decl": "int seed"
        }
      ]
    }
  ],
  "methodmaps": [],
  "enums": [],
  "constants": [],
  "typesets": [],
  "typedefs": []
}