{
  "functions": [
    {
      "name": "FloatMul",
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "oper1",
          "decl": "float oper1"
        },
        {
          "type": "float",
          "name": "oper2",
          "decl": "float oper2"
        }
      ]
    },
    {
      "name": "FloatDiv",
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "dividend",
          "decl": "float dividend"
        },
        {
          "type": "float",
          "name": "divisor",
          "decl": "float divisor"
        }
      ]
    },
    {
      "name": "FloatAdd",
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "oper1",
          "decl": "float oper1"
        },
        {
          "type": "float",
          "name": "oper2",
          "decl": "float oper2"
        }
      ]
    },
    {
      "name": "FloatSub",
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "oper1",
          "decl": "float oper1"
        },
        {
          "type": "float",
          "name": "oper2",
          "decl": "float oper2"
        }
      ]
    },
    {
      "name": "FloatFraction",
      "docStart": 3902,
      "docEnd": 4032,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "RoundToZero",
      "docStart": 4078,
      "docEnd": 4233,
      "kind": "native",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "RoundToCeil",
      "docStart": 4275,
      "docEnd": 4433,
      "kind": "native",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "RoundToFloor",
      "docStart": 4475,
      "docEnd": 4632,
      "kind": "native",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "RoundToNearest",
      "docStart": 4675,
      "docEnd": 4807,
      "kind": "native",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "FloatCompare",
      "docStart": 4852,
      "docEnd": 5219,
      "kind": "native",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "fOne",
          "decl": "float fOne"
        },
        {
          "type": "float",
          "name": "fTwo",
          "decl": "float fTwo"
        }
      ]
    },
    {
      "name": "SquareRoot",
      "docStart": 5273,
      "docEnd": 5460,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "Pow",
      "docStart": 5503,
      "docEnd": 5710,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        },
        {
          "type": "float",
          "name": "exponent",
          "decl": "float exponent"
        }
      ]
    },
    {
      "name": "Exponential",
      "docStart": 5762,
      "docEnd": 5898,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "Logarithm",
      "docStart": 5942,
      "docEnd": 6151,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        },
        {
          "type": "float",
          "name": "base",
          "decl": "float base"
        }
      ]
    },
    {
      "name": "Sine",
      "docStart": 6210,
      "docEnd": 6346,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "Cosine",
      "docStart": 6383,
      "docEnd": 6521,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "Tangent",
      "docStart": 6560,
      "docEnd": 6699,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "FloatAbs",
      "docStart": 6739,
      "docEnd": 6874,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "ArcTangent",
      "docStart": 6915,
      "docEnd": 7061,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "angle",
          "decl": "float angle"
        }
      ]
    },
    {
      "name": "ArcCosine",
      "docStart": 7104,
      "docEnd": 7249,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "angle",
          "decl": "float angle"
        }
      ]
    },
    {
      "name": "ArcSine",
      "docStart": 7291,
      "docEnd": 7434,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "angle",
          "decl": "float angle"
        }
      ]
    },
    {
      "name": "ArcTangent2",
      "docStart": 7474,
      "docEnd": 7669,
      "kind": "native",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "x",
          "decl": "float x"
        },
        {
          "type": "float",
          "name": "y",
          "decl": "float y"
        }
      ]
    },
    {
      "name": "RoundFloat",
      "docStart": 7718,
      "docEnd": 7928,
      "kind": "stock",
      "returnType": "int",
      "arguments": [
        {
          "type": "float",
          "name": "value",
          "decl": "float value"
        }
      ]
    },
    {
      "name": "DegToRad",
      "docStart": 11635,
      "docEnd": 11748,
      "kind": "stock",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "angle",
          "decl": "float angle"
        }
      ]
    },
    {
      "name": "RadToDeg",
      "docStart": 11824,
      "docEnd": 11937,
      "kind": "stock",
      "returnType": "float",
      "arguments": [
        {
          "type": "float",
          "name": "angle",
          "decl": "float angle"
        }
      ]
    },
    {
      "name": "GetURandomInt",
      "docStart": 12013,
      "docEnd": 12202,
      "kind": "native",
      "returnType": "int",
      "arguments": []
    },
    {
      "name": "GetURandomFloat",
      "docStart": 12235,
      "docEnd": 12447,
      "kind": "native",
      "returnType": "float",
      "arguments": []
    },
    {
      "name": "SetURandomSeed",
      "docStart": 12484,
      "docEnd": 12758,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "const int[]",
          "name": "seeds",
          "decl": "const int[] seeds"
        },
        {
          "type": "int",
          "name": "numSeeds",
          "decl": "int numSeeds"
        }
      ]
    },
    {
      "name": "SetURandomSeedSimple",
      "docStart": 12824,
      "docEnd": 13011,
      "kind": "stock",
      "returnType": "void",
      "arguments": [
        {
          "type": "int",
          "name": "seed",
          "decl": "int seed"
        }
      ]
    }
  ],
  "methodmaps": [],
  "enums": [],
  "constants": [],
  "typesets": [],
  "typedefs": []
}