{
  "functions": [
    {
      "name": "SetVariantBool",
      "docStart": 1624,
      "docEnd": 1722,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "bool",
          "name": "val",
          "decl": "bool val"
        }
      ]
    },
    {
      "name": "SetVariantString",
      "docStart": 1762,
      "docEnd": 1857,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "const char[]",
          "name": "str",
          "decl": "const char[] str"
        }
      ]
    },
    {
      "name": "SetVariantInt",
      "docStart": 1907,
      "docEnd": 2009,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "int",
          "name": "val",
          "decl": "int val"
        }
      ]
    },
    {
      "name": "SetVariantFloat",
      "docStart": 2047,
      "docEnd": 2155,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "float",
          "name": "val",
          "decl": "float val"
        }
      ]
    },
    {
      "name": "SetVariantVector3D",
      "docStart": 2197,
      "docEnd": 2295,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "const float[3]",
          "name": "vec",
          "decl": "const float vec[3]"
        }
      ]
    },
    {
      "name": "SetVariantPosVector3D",
      "docStart": 2349,
      "docEnd": 2465,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "const float[3]",
          "name": "vec",
          "decl": "const float vec[3]"
        }
      ]
    },
    {
      "name": "SetVariantColor",
      "docStart": 2522,
      "docEnd": 2615,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "const int[4]",
          "name": "color",
          "decl": "const int color[4]"
        }
      ]
    },
    {
      "name": "SetVariantEntity",
      "docStart": 2666,
      "docEnd": 2808,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "int",
          "name": "entity",
          "decl": "int entity"
        }
      ]
    }
  ],
  "methodmaps": [],
  "enums": [],
  "constants": [],
  "typesets": [],
  "typedefs": []
}