{
  "functions": [
    {
      "name": "AcceptEntityInput",
      "docStart": 1661,
      "docEnd": 2202,
      "kind": "native",
      "returnType": "bool",
      "arguments": [
        {
          "type": "int",
          "name": "dest",
          "decl": "int dest"
        },
        {
          "type": "const char[]",
          "name": "input",
          "decl": "const char[] input"
        },
        {
          "type": "int",
          "name": "activator",
          "decl": "int activator"
        },
        {
          "type": "int",
          "name": "caller",
          "decl": "int caller"
        },
        {
          "type": "int",
          "name": "outputid",
          "decl": "int outputid"
        }
      ]
    }
  ],
  "methodmaps": [],
  "enums": [],
  "constants": [],
  "typesets": [],
  "typedefs": []
}