{
  "functions": [
    {
      "name": "SetVariantBool",
      "docStart": 1626,
      "docEnd": 1715,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "bool",
          "name": "val",
          "decl": "bool val"
        }
      ]
    },
    {
      "name": "SetVariantString",
      "docStart": 1755,
      "docEnd": 1841,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "const char[]",
          "name": "str",
          "decl": "const char[] str"
        }
      ]
    },
    {
      "name": "SetVariantInt",
      "docStart": 1891,
      "docEnd": 1984,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "int",
          "name": "val",
          "decl": "int val"
        }
      ]
    },
    {
      "name": "SetVariantFloat",
      "docStart": 2022,
      "docEnd": 2121,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "float",
          "name": "val",
          "decl": "float val"
        }
      ]
    },
    {
      "name": "SetVariantVector3D",
      "docStart": 2163,
      "docEnd": 2252,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "const float[3]",
          "name": "vec",
          "decl": "const float vec[3]"
        }
      ]
    },
    {
      "name": "SetVariantPosVector3D",
      "docStart": 2306,
      "docEnd": 2413,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "const float[3]",
          "name": "vec",
          "decl": "const float vec[3]"
        }
      ]
    },
    {
      "name": "SetVariantColor",
      "docStart": 2470,
      "docEnd": 2556,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "const int[4]",
          "name": "color",
          "decl": "const int color[4]"
        }
      ]
    },
    {
      "name": "SetVariantEntity",
      "docStart": 2607,
      "docEnd": 2729,
      "kind": "native",
      "returnType": "void",
      "arguments": [
        {
          "type": "int",
          "name": "entity",
          "decl": "int entity"
        }
      ]
    }
  ],
  "methodmaps": [],
  "enums": [],
  "constants": [],
  "typesets": [],
  "typedefs": []
}